Add tests for error functions.
The ProxyError test currently panics because of a bug in ProxyError.

--- FAIL: TestErrors (0.00s)
panic: keyword "PROXY-ERROR %s\n" contains forbidden bytes [recovered]
        panic: keyword "PROXY-ERROR %s\n" contains forbidden bytes